### ISSUE TITLE
Panic when parsing invalid subnet addresses with Ipv4Pool::from()

### ISSUE THREAD

**Issue by Payn** [rikonaka/subnetwork-rs#1]
Passing any invalid subnet address into Ipv4Pool::from causes panic instead of returning InvalidInputError.
Only validation that's done is if the input string contains "/". IP nor prefix length aren't validated at all.

All of these will cause program to crash

```
use std::net::Ipv4Addr;
use subnetwork::Ipv4Pool;

fn main() 
{
    let _pool1 = Ipv4Pool::from("1.2.3.4/33");
    let _pool2 = Ipv4Pool::from("1.2.3.4/");
    let _pool3 = Ipv4Pool::from("nonip/24");
}
```

**Comment by rikonaka** [comment]
I will fix that soon 😉

**Comment by rikonaka** [comment]
Hi, the newest version of `subnetwork` has fix this bugs now. 😉

https://github.com/rikonaka/subnetwork-rs/blob/ec335da9fb66816b3d37f60b8d1fcffa3aa28c92/src/lib.rs#L962-L966
